### ISSUE TITLE
Abandoned Repo?

### ISSUE THREAD

**Issue by unixneo** [nileshtrivedi/openai#4]
Has this repo been abandoned?

I notice that `ruby-openai` is actively developed and works in practice.

This gem `openai` is not actively developed and does not work in practice.

**Comment by nileshtrivedi** [comment]
@unixneo I ended up converting my Rails project that used this into a Javascript-only app. So, yeah, I haven't needed this library in quite a while. But PRs, fixes/features are still welcome.

**Comment by nileshtrivedi** [comment]
I just merged a PR and pushed new version as 0.3.0 to rubygems.org.
