### ISSUE TITLE
Bruh! you shouldn't be squading on this name

### ISSUE THREAD

**Issue by soheil** [nileshtrivedi/openai#9]
Please either maintain the pkg or archive the gem so people are not wasting time dealing with a non-working lib.

**Comment by ashgkwd** [comment]
This project and gem should be archived.

To all those who reached here from [OpenAI recommendation](https://platform.openai.com/docs/libraries/community-libraries), please consider using well maintained https://github.com/alexrudall/ruby-openai

**Comment by daBee** [comment]
*Squatting

**Comment by nileshtrivedi** [comment]
Oh wow, I didn't see this issue till now at all.

Confirming that this package is not maintained. I will archive the repo.

I will also reach out to OpenAI team and transfer the "openai" rubygems identity to them so that they could deal with it in a way that's most appropriate.

**Comment by alexrudall** [comment]
Hey @nileshtrivedi , thanks for this :) I'd be happy to switch the ruby-openai gem to the namespace if you/openai were happy with it.

**Comment by nileshtrivedi** [comment]
@alexrudall Yeah, I'm okay with it.

I tried posting this in the OpenAI discord but hit some rule against posting non-whitelisted URLs.
I pinged Greg on Twitter but don't think he saw it: https://twitter.com/nileshtrivedi/status/1758841650334294447

If you can help me get some attention from someone on OpenAI staff, it would be helpful.

**Comment by nileshtrivedi** [comment]
Comment in openai discord: https://discord.com/channels/974519864045756446/1037561178286739466/1208637169716043807

**Comment by alexrudall** [comment]
@nileshtrivedi DMd you on twitter

**Comment by sferik** [comment]
I’m planning to revive this library. Commits coming soon.

**Comment by nileshtrivedi** [comment]
@sferik If you'll be able to maintain this gem, I'm happy to transfer this github repo to you. You also already have the gem ownership in Rubygems.

**Comment by sferik** [comment]
I'm actively working on this gem now. Closing this issue.
